import Navbar from "@/components/navbar/navbar";
import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Civil Service",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/Civil_Service_University_(Ethiopia).png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
